### ISSUE TITLE
LV_Connect Fingerprint where to get

### ISSUE THREAD

**Issue by blaqone** [skobkars/lvconnect#1]
Where can I get the fingerprint?

LVCONNECT_FINGERPRINT - Your LibreView account's fingerprint for skipping 2FA code verification step.

Thank you

**Comment by skobkars** [comment]
Fingerprint is the LibreView feature that allows users to skip 2-Factor Authentication by "remembering" their browser's "fingreprint" on the server side. That is how "remember me" checkbox works.

Basically, you need to use network traffic inspector of your browser to find the generated Fingerprint. In case of Chrome for example use Right+Click -> Inspect option and then switch to Network tab.

After successful login with selected "remember me" option your browser will be sending an extra field 'fingerprint' when POST'ing data to /auth/login path. Something like this:

```
HEADERS:
Request URL: https://api-eu.libreview.io/auth/login
Request Method: POST
....

PAYLOAD:
{
    "email": "<your email address>",
    "password": "<your password>",
    "fingerprint": "2,(Macintosh;IntelMacOSX__)AppleWebKit/(KHTML,likeGecko)Chrome/Safari/,Mozilla/...."
}
```

You need that string "2,....".

Few notes:

1. LibreView holds information about your browser in active state as long as your login session is active, and deletes it if you log out or your session in browser expires (defaults to 2 hours). So in order for your lvconnect to work indefinitely, you should never log out of the browser session or let it expire. Just close the browser tab when you done.

2. If you session has expired and lvconnect stopped working, just open that same browser again, log in to your account and close the tab. lvconnect should start working again.

3. Keep LVCONNECT_INTERVAL short enough for the session to stay active indefinitely. If it is longer than 2 hours you session _will_ expire.
