### ISSUE TITLE
What do I miss in the setup?

### ISSUE THREAD

**Issue by LettiNightscout** [skobkars/lvconnect#2]
Hi, I am trying to set up your plugin to a Nightscout instance. Unfortunately I could not manage to make it work, I'd really appreciate if you could help me making this work! My 8 years old son has a Libre 3 and it would be really cool to have the data in Nightscout so I'd transfer them to a smartwatch. 

I was doing the following:

1. Deployed to Heroku from GitHub forked Nightscout repo (one file uploaded, other is replaced as per instructions in your repo) -> No option to add other parameters here
2. Added “lvconnect” to ENABLE and SHOW_PLUGINS fields when doing the deploy
3. So now I have a working NS site
4. Now Heroku app is there, I went to Settings/Reveal Configs and added the following variables (here it is possible to add variables):
i.	WEBSITE_HOSTNAME – it is clear what to enter here as a value
ii.	LVCONNECT_SERVER – this is not that clear, I’ve added 'EU'
iii.	LVCONNECT_USER_NAME – this is also clear, the user name (email address) I have for LibreView
iv.	LVCONNECT_PASSWORD – also clear
v.	LVCONNECT_FINGERPRINT – I have signed in to the LibreView, pressed F12, under the “Session Storage” there was a token. I have taken that really long text – tried with and without the “-s
vi.	LVCONNECT_INTERVAL – set to 120,000 (2 min – I am using Libre 3 which has data in each min, so I wanted to start with a 2 min here)
vii.	LVCONNECT_FIRST_FULL_DAYS – 10 (no need for more)

One more question: what is the difference if I add WEBSITE_HOSTNAME or NS? I'v tried adding NS also but still not working.

**Comment by adarbac** [comment]
Push :) Please add setup instruction on how to use your script with Nightscout running on Heroku

**Comment by skobkars** [comment]
> One more question: what is the difference if I add WEBSITE_HOSTNAME or NS? I'v tried adding NS also but still not working.

**Important!!! The only Nightscout version that was tested and has been up and running with lvconnect for more than two months now is 14.1.0.**

**Current version of Nightsout in Github has its bootevent.js file changed in comparison to 14.1.0, so replacing it with the lvconnect one may break Nightscout, and you should stick to v 14.1.0 until Nightscout integrates lvconnect into their codebase as an official plugin.**

Also, I never used Heroku hosting for lvconnect and cannot really recommend you how to set it up properly there until I test it myself, sorry.

That said, if you have Nightscout 14.1.0 and configured it as described, then the only incorrect value is LVCONNECT_FINGERPRINT. You used authentication token, but need your browser's "fingerprint" that is generated and sent to LV after you activate "remember me" option for your LV account. It is used for skipping 2-Factor Authentication, not authentication itself.

**Please see skobkars/lvconnect#1 for the details on how to get the fingerprint and for the caveats on how to use it properly with lvconnect.**

Setting LVCONNECT_INTERVAL shorter than 15 minutes will make little difference I'm afraid. The data that is included into LibreView reports is spaced 15 min apart even for v3. _But I would appreciate it very much if you let me know how 2 minutes interval works for you. v3 is not available in our country yet, so we only tested it with one v3 device in Europe so far._

I do not know how come that Nightscout has both WEBSITE_HOSTNAME and NS, but I just followed their instructions on setting variables. It may have to do with different client devices, but this is just my guess.

**Comment by skobkars** [comment]
> Push :) Please add setup instruction on how to use your script with Nightscout running on Heroku

I will need to try that myself first, but do not have enough of free time currently. Will get back here if/when I test it.

My hope is that lvconnect is made part of the Nightscout soon, and you won't need to do separate installs.

**Comment by skobkars** [comment]
> Hi, I am trying to set up your plugin to a Nightscout instance. Unfortunately I could not manage to make it work, I'd really appreciate if you could help me making this work! My 8 years old son has a Libre 3 and it would be really cool to have the data in Nightscout so I'd transfer them to a smartwatch.
> 
> I was doing the following:
> 
> 1. Deployed to Heroku from GitHub forked Nightscout repo (one file uploaded, other is replaced as per instructions in your repo) -> No option to add other parameters here
> 2. Added “lvconnect” to ENABLE and SHOW_PLUGINS fields when doing the deploy
> 3. So now I have a working NS site
> 4. Now Heroku app is there, I went to Settings/Reveal Configs and added the following variables (here it is possible to add variables):
>    i.	WEBSITE_HOSTNAME – it is clear what to enter here as a value
>    ii.	LVCONNECT_SERVER – this is not that clear, I’ve added 'EU'
>    iii.	LVCONNECT_USER_NAME – this is also clear, the user name (email address) I have for LibreView
>    iv.	LVCONNECT_PASSWORD – also clear
>    v.	LVCONNECT_FINGERPRINT – I have signed in to the LibreView, pressed F12, under the “Session Storage” there was a token. I have taken that really long text – tried with and without the “-s
>    vi.	LVCONNECT_INTERVAL – set to 120,000 (2 min – I am using Libre 3 which has data in each min, so I wanted to start with a 2 min here)
>    vii.	LVCONNECT_FIRST_FULL_DAYS – 10 (no need for more)
> 
> One more question: what is the difference if I add WEBSITE_HOSTNAME or NS? I'v tried adding NS also but still not working.

**Comment by LettiNightscout** [comment]
Hi!
Thanks for your kind help!
I have managed to get the proper fingerprint information and reverted back to 14.1.0 (complete new deploy), but still could not make it work, so cannot give you feedback about the 2min interval case.
I do not know what is the problem, I am doing the basic Heroku deploy from the Nightscout repo. Maybe I should try my own deploy not using the built-in one, but I have to learn a lot about these things before I can even start thinking about it. 
But if someone figured out, please comment!
Thanks

**Comment by skobkars** [comment]
Hi all,

I've just made changes to the repo and added 'Deploy to Heroku' button and instructions. Current version of the tool is 0.1.6.

I am not sure if the process will be running on Heroku without 'inactivity interruptions' yet, but will keep an eye on it for a day or two and see what is happening. Until then, I cannot guaranty that all the deployment issues have been resolved, sorry.

I also added `LVCONNECT_TIME_OFFSET` variable that tells to the Heroku app which timezone you are in (but in minutes, not hours!). This is required, as LibreView does not bother using timezones internally in their report module, and there is no way of telling what time shift should be applied to all data timestamps. This is taken care by your browser when lvconnect is used as a Nightscout plugin, but not when it is ran as a standalone tool.

Having the tool running independently removes restriction on the Nighstcout version.

Hopefully, lvconnect is added as a standard NS plugin in the future.

Cheers,

**Comment by skobkars** [comment]
> Hi all,
> 
> I've just made changes to the repo and added 'Deploy to Heroku' button and instructions. Current version of the tool is 0.1.6.
> 
> I am not sure if the process will be running on Heroku without 'inactivity interruptions' yet, but will keep an eye on it for a day or two and see what is happening. Until then, I cannot guaranty that all the deployment issues have been resolved, sorry.
> 
> I also added `LVCONNECT_TIME_OFFSET` variable that tells to the Heroku app which timezone you are in (but in minutes, not hours!). This is required, as LibreView does not bother using timezones internally in their report module, and there is no way of telling what time shift should be applied to all data timestamps. This is taken care by your browser when lvconnect is used as a Nightscout plugin, but not when it is ran as a standalone tool.
> 
> Having the tool running independently removes restriction on the Nighstcout version.
> 
> Hopefully, lvconnect is added as a standard NS plugin in the future.
> 
> Cheers,

The Heroku deployed app is running just fine it seems, no issues. However, I first deployed it on the EU servers and it could not connect to the LibreView servers after the first success for some reason. US-based deployment has no such problem ... so far.

**Comment by LettiNightscout** [comment]
Thank your very much! Working now!
Feedback on the Libre3: 5 min data is available from LibreView, so 2 min interval can be changed to 5 min.

**Comment by skobkars** [comment]
Great, thank you for the update on v3.
