### ISSUE TITLE
where to find LVCONNECT_FINGERPRINT 

### ISSUE THREAD

**Issue by srossross** [skobkars/lvconnect#4]
I came across this project from a google search and I am looking for how to get the required parameter `LVCONNECT_FINGERPRINT`

**Comment by skobkars** [comment]
Please see the answer in the closed issues: https://github.com/skobkars/lvconnect/issues/1#issuecomment-1019599427

That said, I've just uploaded fresh version of this repo to the code to adapt to the recent changes in LV code, so please make sure you are using the latest version.
